### PR TITLE
Implement sort and maxResults

### PR DESCRIPTION
**Pull request by pwaller**
See also: alphagov/gapy#6

### CODE REVIEW

**Comment by pwaller** [comment]
This one is ready for merging at will, @robyoung.

**Comment by pwaller** [comment]
We'll need to tag gapy and update the requirements here before too long; however, there are more features in the pipeline so I don't know if you want to wait on that.

**Comment by robyoung** [comment]
Surely this can't be merged until the gapy version has been updated. It's depending on sort and maxResults.

**Comment by pwaller** [comment]
Good spot. Yes, gapy needs updating and tagging, then I'll update `requirements.txt`.

Apologies if sending the pull request before that point is contrary to protocol, but I wanted to get the intent out in public early.

**Comment by fawkesley** [comment]
Please reopen when this needs reviewing :)

**Comment by pwaller** [comment]
@paulfurley please reopen now, I've pushed the remaining fix.

**Comment by pwaller** [comment]
(I can't reopen as I'm not an owner of the repo)

**Comment by pwaller** [comment]
@robyoung gapy appears to be missing a 1.1.0 tag. On a side note, how do you prefer it specified in the requirements? as a git+ URL makes it easier for one to switch the versions around and clone it locally but maybe pypi is better?

**Comment by pwaller** [comment]
I've switched to pypi so that the build may have a chance of passing.

**Pull request merged**
