### PR TITLE
Add plugin architecture

### PR DESCRIPTION
**Pull request by pwaller**
This pull request adds a new plugin mechanism.

It currently depends on the `backdrop-collector-plugins` package, which
hasn't yet been reviewed.

The basic idea is that it should be possible to perform arbitrary
transformations to the documents before they are stamped with a `humanId`.

These arbitrary transformations may perform an aggregation on the input
and so need to see all input documents and specify the complete output
document set.

``` json
{
  "dataType": "content_dashboard_visitors_count",
  "query": {
    "id": "ga:123456",
    "metrics": [
      "visitors"
    ],
    "dimensions": [
      "customVarValue9"
    ]
  },
  "target": {
    "url": "http://localhost:3039/data/foo/visitors-count",
    "token": "foo-bearer-token"
  },
  "plugins": [
    "ComputeDepartmentKey('customVarValue9')",
    "RemoveKey('customVarValue9')",
    "AggregateKey(aggregate_count('visitors'))"
  ]
}
```

The above query configuration shows the new "plugins" configuration
option. If "plugins" is specified, then `backdrop.collector.plugins` is
required to run.

In the example above, plugins are run in turn on all documents, in the order
they are provided. `ComputeDepartmentKey` computes a new `department`
parameter for each document based on the content of `customVarValue9`,
`RemoveKey` deletes the old `customVarValue9`. Finally, because there was
a many-to-one mapping of `customVarValue9` to `department`, the `visitors`
count needs to be summed for documents where all values except `visitors`
are equal. This is achieved through `AggregateKey`, which is capable
of aggregating multiple fields as well as different types of fields.
`aggregate_count` in this case specifies that the aggreagtion should happen
using the `sum` builtin. `aggregate_rate('rate_var', 'count_var')` allows
aggregation of percentages, weighted by counts.

Plugin strings are python expressions evaluated in the
[`backdrop.collector.plugins`](https://github.com/scraperwiki/backdrop-collector-plugins/blob/master/backdrop/collector/plugins/__init__.py) namespace.

### CODE REVIEW

**Comment by pwaller** [comment]
Rebased. Implementation is still to come, since it requires another change that hadn't occurred to me.

**Comment by robyoung** [comment]
Could we get an update to the README please?

**Comment by pwaller** [comment]
I've added a link to `backdrop-collector-plugins` and [send a pull request to document it there](https://github.com/alphagov/backdrop-collector-plugins/pull/8).

**Comment by robyoung** [comment]
I think that detailed documentation is really great. We have high level documentation about what configuration options are available in the GA collector's README. Could you add something there just to let readers know that there is such an option and what it's for?

**Comment by pwaller** [comment]
@robyoung see 79dfff8 and c8dfb6e. Let me know if there are any changes needed to https://github.com/alphagov/backdrop-collector-plugins/pull/8.

**Comment by pwaller** [comment]
I had a spurious comma in c8dfb6e, forced 55cbd36 to fix it.

**Comment by pwaller** [comment]
Uh oh, cowboy merge, the tests failed! :tongue:

**Comment by pwaller** [comment]
Not sure how. [`nose.tools.assert_in` doesn't exist](https://travis-ci.org/alphagov/backdrop-ga-collector/jobs/21927239#L244).. what?

**Comment by robyoung** [comment]
What the hell!? But it was just documentation changes!

**Comment by pwaller** [comment]
Can we put this down to a travis oddity? I don't understand what's happened here.

**Comment by robyoung** [comment]
Agreed. If it happens again we can take a closer look. Not great that we're not confident about our CI though :grimacing:

**Comment by pwaller** [comment]
I understand what happened.

You merged it before travis could [fetch the merge ref](https://travis-ci.org/alphagov/backdrop-ga-collector/jobs/21927240#L12).

Python2.6 is broken because [`nose.tools`](https://github.com/nose-devs/nose/blob/master/nose/tools/trivial.py#L46) gets its `assert_foo` methods dynamically from `unittest` which [gained assertIn in 2.7](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIn).

Can we remove python2.6 from the list of supported versions? What is used in production?

**Pull request merged**
