### PR TITLE
Fix #35

### LINKED ISSUE #35: `raise ValueError` should give explanation
In particular:

https://github.com/alphagov/backdrop-ga-collector/blob/master/collector/datetimeutil.py#L20

### PR DESCRIPTION
**Pull request by pwaller**
/cc @robyoung

### CODE REVIEW

**Comment by pwaller** [comment]
I did also grep around for other abuses but didn't find any in this repository.

**Comment by jcbashdown** [comment]
I know it's trivial but I reckon this should have tests?

**Comment by pwaller** [comment]
If tests are considered necessary here, I believe that's outside the scope of this pull request which demonstrably only improves the quality of already existing error conditions which are programmer facing anyway. With something like this the additional friction of needing to introduce tests outweighs the benefit of attempting to improve what happens when there are failures (which is my intention here). If it's considered an issue it should be a new one.

**Comment by fawkesley** [comment]
Agree that there should (already) be tests but this is absolutely an improvement without.

**Pull request merged**
